package com.robotsn;
import java.util.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api")
public class AdminApi {
 final Store s;final PasswordEncoder passwords;final BindingService bindings;
 public AdminApi(Store s,PasswordEncoder passwords,BindingService bindings){this.s=s;this.passwords=passwords;this.bindings=bindings;}
 @GetMapping("/users") Object users(){s.admin();var rows=s.db.queryForList("select u.username,u.user_id,u.role,u.active,u.sn_permission,u.scope_sns,u.created_at,u.auth_version,b.robot_id bound_robot_id,r.sn bound_sn,r.fields->>'customer' customer_name from sys_user u left join user_robot_binding b on b.user_id=u.user_id left join robot r on r.robot_id=b.robot_id order by u.username");rows.forEach(r->r.put("scope_sns",s.decode(r.get("scope_sns"))));return rows;}
 @GetMapping("/users/binding-history") Object bindingHistory(){s.admin();return s.db.queryForList("select h.*,u.username,old.sn old_sn,n.sn new_sn from binding_history h join sys_user u on u.user_id=h.user_id left join robot old on old.robot_id=h.old_robot_id left join robot n on n.robot_id=h.new_robot_id order by h.id desc");}
 @PostMapping("/users") @Transactional Object createUser(@RequestBody Map<String,Object>b){s.admin();s.db.execute("select pg_advisory_xact_lock(8712026)");String u=s.required(b,"username");if(!u.matches("[a-zA-Z0-9_.-]{3,64}"))Store.fail(400,"账号须为 3–64 位字母、数字或 ._-");String password=s.required(b,"password");validatePassword(password);String role=role(b);Object scope=scope(b,role);String why=s.required(b,"reason");s.db.update("insert into sys_user(username,password_hash,role,sn_permission,scope_sns,active) values (?,?,?,?,?::jsonb,?)",u,passwords.encode(password),role,role.equals("TECHNICIAN")&&Boolean.TRUE.equals(b.get("snPermission")),s.encode(scope),!b.containsKey("active")||Boolean.TRUE.equals(b.get("active")));bindings.update(u,b,why);s.audit("user",u,"CREATE","permissions",null,safe(b),why);return Map.of("username",u);}
 String role(Map<String,Object>b){String r=s.required(b,"role");if(!Set.of("ADMIN","TECHNICIAN","USER").contains(r))Store.fail(400,"无效角色");return r;}
 void validatePassword(String p){if(p.length()<12||p.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>72)Store.fail(400,"密码至少 12 个字符，UTF-8 不超过 72 字节");}
 Object scope(Map<String,Object>b,String role){Object value=b.getOrDefault("scopeSns",List.of());if(!(value instanceof List<?>))Store.fail(400,"技术人员范围须为 SN 数组");if(!role.equals("TECHNICIAN")){if(!((List<?>)value).isEmpty())Store.fail(400,"普通用户请使用单台机器人绑定，不能设置 SN 列表");return List.of();}for(Object item:(List<?>)value)if(!(item instanceof String)||s.db.queryForObject("select count(*) from robot where sn=? and not deleted",Integer.class,s.resolve(item.toString()))==0)Store.fail(400,"技术人员范围包含不存在的机器人");return value;}
 Map<String,Object> safe(Map<String,Object>b){var out=new LinkedHashMap<String,Object>();for(String key:List.of("role","active","snPermission","scopeSns","boundRobotId","customerName"))if(b.containsKey(key))out.put(key,b.get(key));return out;}
 @PatchMapping("/users/{u}") @Transactional Object changeUser(@PathVariable String u,@RequestBody Map<String,Object>b){s.admin();s.db.execute("select pg_advisory_xact_lock(8712026)");var old=s.one("select username,user_id,role,active,sn_permission,scope_sns,auth_version from sys_user where username=? for update",u);String role=b.containsKey("role")?role(b):old.get("role").toString();boolean active=b.containsKey("active")?Boolean.TRUE.equals(b.get("active")):Boolean.TRUE.equals(old.get("active"));if(u.equals(s.actor())&&(!active||!role.equals("ADMIN")))Store.fail(409,"不能在当前会话停用或降级自己");if(old.get("role").equals("ADMIN")&&Boolean.TRUE.equals(old.get("active"))&&(!active||!role.equals("ADMIN"))&&s.db.queryForObject("select count(*) from sys_user where role='ADMIN' and active",Integer.class)<=1)Store.fail(409,"必须保留至少一个有效管理员");
   String why=s.required(b,"reason");boolean snPermission=role.equals("TECHNICIAN")&&(b.containsKey("snPermission")?Boolean.TRUE.equals(b.get("snPermission")):Boolean.TRUE.equals(old.get("sn_permission")));Object scopes=b.containsKey("scopeSns")?scope(b,role):role.equals("TECHNICIAN")?s.decode(old.get("scope_sns")):List.of();String p=s.text(b,"password");boolean invalidate=!role.equals(old.get("role"))||active!=Boolean.TRUE.equals(old.get("active"))||!p.isBlank();
   s.db.update("update sys_user set role=?,active=?,sn_permission=?,scope_sns=?::jsonb,auth_version=auth_version+? where username=?",role,active,snPermission,s.encode(scopes),invalidate?1:0,u);
   if(!p.isBlank()){validatePassword(p);s.db.update("update sys_user set password_hash=? where username=?",passwords.encode(p),u);s.audit("user",u,"PASSWORD_RESET","password",null,"密码已重置",why);}
   bindings.update(u,b,why);old.put("scope_sns",s.decode(old.get("scope_sns")));s.audit("user",u,"PERMISSION","permissions",old,safe(b),why);return Map.of("username",u);
 }
 @PostMapping("/password") @Transactional Object password(@RequestBody Map<String,Object>b){String old=s.required(b,"oldPassword"),next=s.required(b,"newPassword");String hash=s.db.queryForObject("select password_hash from sys_user where username=?",String.class,s.actor());if(!passwords.matches(old,hash))Store.fail(400,"当前密码不正确");validatePassword(next);s.db.update("update sys_user set password_hash=?,auth_version=auth_version+1 where username=?",passwords.encode(next),s.actor());s.audit("user",s.actor(),"PASSWORD","password",null,"已变更","本人修改密码");return Map.of("message","密码已修改，请重新登录");}
 @GetMapping("/audit") Object audit(){s.technical();var a=s.account();var rows=s.db.queryForList("select * from audit_log where ?='ADMIN' or actor=? or object_type='robot' order by id desc",s.role(),s.actor());var allowed=new HashSet<String>();s.db.queryForList("select * from robot").stream().filter(s::allowed).forEach(r->allowed.add(r.get("sn").toString()));return rows.stream().filter(r->s.role().equals("ADMIN")||r.get("actor").equals(s.actor())||allowed.contains(s.resolve(r.get("object_id").toString()))).limit(2000).map(r->{r.put("old_value",s.decode(r.get("old_value")));r.put("new_value",s.decode(r.get("new_value")));return r;}).toList();}
 @GetMapping("/logins") Object logins(){s.admin();return s.db.queryForList("select * from login_log order by id desc limit 2000");}
 @GetMapping("/sources") Object sources(){s.technical();var a=s.account();if(!s.role().equals("ADMIN")&&(!((List<?>)s.decode(a.get("scope_sns"))).isEmpty()||!a.get("scope_customer").toString().isBlank()))Store.fail(403,"原始表包含全量数据，仅无范围限制的技术人员和管理员可查看");var imports=s.db.queryForList("select * from source_import order by id desc");imports.forEach(r->{r.put("report",s.decode(r.get("report")));var sheets=s.db.queryForList("select name,cells from source_sheet where import_id=? order by id",r.get("id"));sheets.forEach(x->x.put("cells",s.decode(x.get("cells"))));r.put("sheets",sheets);});return imports;}
 @PutMapping("/settings/{key}") @Transactional Object settings(@PathVariable String key,@RequestBody Map<String,Object>b){s.admin();Object value=b.get("value");var old=s.one("select value from settings where key=? for update",key);if(key.equals("sn_rule")){var rule=s.map(value);if(!"LBR".equals(rule.get("prefix")))Store.fail(400,"确认版固定使用 LBR 前缀");Object types=rule.get("types");if(!(types instanceof List<?> ts)||ts.isEmpty()||!List.of("S","P","M","R").containsAll(ts))Store.fail(400,"生产类型仅支持 S/P/M/R");int max=((Number)rule.get("maxSequence")).intValue();Integer used=s.db.queryForObject("select coalesce(max(last_seq),0) from sn_counter",Integer.class);if(max<Math.max(1,used)||max>9999)Store.fail(400,"流水号上限须介于已分配最大值和 9999 之间");value=Map.of("prefix","LBR","types",types,"maxSequence",max);}
   else if(key.equals("statuses")){if(!(value instanceof List<?> v)||v.isEmpty()||v.stream().anyMatch(x->!(x instanceof String)||x.toString().isBlank()||x.toString().length()>40)||!v.containsAll(List.of("在库","维修中","已报废","已出库","已交付")))Store.fail(400,"保留在库、维修中、已报废、已出库、已交付等流程状态");}
   else if(key.equals("module_slots")){var slots=s.map(value);if(slots.isEmpty())Store.fail(400,"模组字典不可为空");for(var e:slots.entrySet())if(e.getKey().isBlank()||!(e.getValue() instanceof Number n)||n.intValue()<1||n.intValue()>100)Store.fail(400,"模组数量须为 1–100");for(var r:s.db.queryForList("select slot,max(c) qty from (select slot,robot_sn,count(*) c from module_installation where removed_at is null group by slot,robot_sn) a group by slot")){if(!slots.containsKey(r.get("slot"))||((Number)slots.get(r.get("slot"))).intValue()<((Number)r.get("qty")).intValue())Store.fail(409,"字典必须容纳当前实际装配的类型与数量");}}
   else Store.fail(400,"该配置不可编辑");s.db.update("update settings set value=?::jsonb where key=?",s.encode(value),key);s.audit("settings",key,"CONFIG","value",s.decode(old.get("value")),value,s.required(b,"reason"));return Map.of("key",key);
 }
 @GetMapping("/tables") Object tables(){s.technical();return s.db.queryForList("select * from business_table where not deleted order by id");}
 @PostMapping("/tables") @Transactional Object createTable(@RequestBody Map<String,Object>b){s.admin();long id=s.db.queryForObject("insert into business_table(name) values (?) returning id",Long.class,s.required(b,"name"));s.audit("table",""+id,"CREATE","name",null,b.get("name"),s.required(b,"reason"));return Map.of("id",id);}
 @DeleteMapping("/tables/{id}") @Transactional Object deleteTable(@PathVariable long id,@RequestBody Map<String,Object>b){s.admin();var table=table(id);s.db.update("update business_table set deleted=true where id=?",id);s.audit("table",""+id,"DELETE","*",table,null,s.required(b,"reason"));return Map.of("id",id);}
 Map<String,Object> table(long id){return s.one("select * from business_table where id=? and not deleted for update",id);}
 @GetMapping("/tables/{id}") Object tableData(@PathVariable long id){s.technical();var t=s.one("select * from business_table where id=? and not deleted",id);t.put("fields",s.db.queryForList("select * from business_field where table_id=? and not deleted order by id",id));var fields=s.db.queryForList("select key from business_field where table_id=? and not deleted",id).stream().map(x->x.get("key").toString()).toList();var rows=s.db.queryForList("select * from business_record where table_id=? and not deleted order by id",id);for(var r:rows){var data=s.map(r.get("data"));data.keySet().retainAll(fields);r.put("data",data);}t.put("records",rows);return t;}
 @PostMapping("/tables/{id}/fields") @Transactional Object tableField(@PathVariable long id,@RequestBody Map<String,Object>b){s.admin();table(id);String key=s.required(b,"key");if(!key.matches("[a-zA-Z][a-zA-Z0-9_]{0,48}"))Store.fail(400,"字段标识须使用字母、数字、下划线");long fid=s.db.queryForObject("insert into business_field(table_id,key,label) values (?,?,?) returning id",Long.class,id,key,s.required(b,"label"));s.audit("table",""+id,"CREATE_FIELD",key,null,b,s.required(b,"reason"));return Map.of("id",fid);}
 @DeleteMapping("/tables/{id}/fields/{fid}") @Transactional Object removeTableField(@PathVariable long id,@PathVariable long fid,@RequestBody Map<String,Object>b){s.admin();table(id);var f=s.one("select * from business_field where id=? and table_id=? and not deleted",fid,id);s.db.update("update business_field set deleted=true where id=?",fid);s.audit("table",""+id,"DELETE_FIELD",f.get("key").toString(),f,null,s.required(b,"reason"));return Map.of("id",fid);}
 Map<String,Object> businessValues(long id,Map<String,Object>b){var values=s.map(b.getOrDefault("data",Map.of()));var keys=s.db.queryForList("select key from business_field where table_id=? and not deleted",id).stream().map(x->x.get("key").toString()).toList();if(!keys.containsAll(values.keySet()))Store.fail(400,"包含不存在或已删除的字段");for(Object value:values.values())if(value!=null&&(!(value instanceof String)||value.toString().length()>4000))Store.fail(400,"业务字段须为不超过 4000 字符的文本");return values;}
 @PostMapping("/tables/{id}/records") @Transactional Object createRecord(@PathVariable long id,@RequestBody Map<String,Object>b){s.technical();table(id);var data=businessValues(id,b);long rid=s.db.queryForObject("insert into business_record(table_id,data) values (?,?::jsonb) returning id",Long.class,id,s.encode(data));s.audit("table",""+id,"CREATE_RECORD","record:"+rid,null,data,s.required(b,"reason"));return Map.of("id",rid);}
 @PatchMapping("/tables/{id}/records/{rid}") @Transactional Object editRecord(@PathVariable long id,@PathVariable long rid,@RequestBody Map<String,Object>b){s.technical();table(id);var record=s.one("select * from business_record where id=? and table_id=? and not deleted for update",rid,id);s.revision(b,record);var old=s.map(record.get("data"));var data=new LinkedHashMap<>(old);data.putAll(businessValues(id,b));s.db.update("update business_record set data=?::jsonb,revision=revision+1 where id=?",s.encode(data),rid);s.audit("table",""+id,"UPDATE_RECORD","record:"+rid,old,data,s.required(b,"reason"));return Map.of("id",rid);}
 @DeleteMapping("/tables/{id}/records/{rid}") @Transactional Object deleteRecord(@PathVariable long id,@PathVariable long rid,@RequestBody Map<String,Object>b){s.admin();table(id);var record=s.one("select * from business_record where id=? and table_id=? and not deleted for update",rid,id);s.revision(b,record);s.db.update("update business_record set deleted=true,revision=revision+1 where id=?",rid);s.audit("table",""+id,"DELETE_RECORD","record:"+rid,s.decode(record.get("data")),null,s.required(b,"reason"));return Map.of("id",rid);}
}
